Repository Dia218/webty-frontend-next, pull requests merged in 2025-03, with the labels that each got.

#194 feat:Voting pannel 추가
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/components/buisness/review/ReviewDetail.tsx
  src/components/buisness/voting/SimilarWebtoonPannel.tsx
  src/components/common/CommentList/CommentItem.stories.tsx
  src/components/common/CommentList/MentionSuggestions.tsx
  src/components/common/LargeReviewList/LargeReviewItem.tsx
  src/components/common/SimilarWebtoonSearchModal/SimilarWebtoonSearchModal.tsx
  src/lib/api/voting/similar.ts
  src/lib/api/voting/vote.ts
  src/lib/types/review/ReviewDetailResponseDto.ts
  src/lib/types/similar/SimilarRequest.ts
  src/lib/types/similar/SimilarResponse.ts
  src/lib/utils/WebSocketContext.tsx
Labels: new-feature

#192 feat : 웹툰디테일페이지 Similar 웹툰 구현
  package-lock.json
  package.json
  src/components/buisness/webtoonDetail/SimilarWebtoonBox.tsx
  src/components/buisness/webtoonDetail/WebtoonDrawerTaps.tsx
  src/components/common/RecommendButton/RecommendButton.tsx
  src/components/ui/progress.tsx
  src/lib/types/similar/SimilarWebtoonDto.ts
Labels: new-feature

#199 fix: Fix FeedPage & Remove NavigationBar CSS
  public/assets/logo.svg
  src/app/feed/page.tsx
  src/components/common/LogInOutDialog/LogInOutDialog.tsx
  src/components/common/NavigationBar/NavigationBar.css
  src/components/common/NavigationBar/NavigationBar.tsx
Labels: refactor

#189 [Search] 검색바 기능구현
  next.config.ts
  public/assets/logo.svg
  src/app/feed/page.tsx
  src/app/search/page.tsx
  src/components/buisness/search/ResultOfReviewSearch.tsx
  src/components/buisness/search/ResultOfWebtoonsSearch.tsx
  src/components/buisness/search/ReviewSearchResult.tsx
  src/components/buisness/search/SearchByAllCategories.tsx
  src/components/buisness/search/SearchByNickName.tsx
  src/components/buisness/search/SearchByReview.tsx
  src/components/buisness/search/SearchByWebtoonName.tsx
  src/components/buisness/search/SearchResultComponent.tsx
  src/components/buisness/search/SortControl.tsx
  src/components/buisness/search/webtoonSearchResult.tsx
  src/components/common/LogInOutDialog/LogInOutDialog.tsx
  src/components/common/NavigationBar/NavigationBar.css
  src/components/common/NavigationBar/NavigationBar.tsx
  src/components/common/Search/SearchBar.tsx
  src/components/common/Search/SearchContainer.tsx
  src/components/common/Search/SearchTab.tsx
  src/components/common/Search/index.ts
  src/lib/api/search/searchApi.ts
  src/lib/api/search/searchMappings.ts
  src/lib/api/search/searchTypes.ts
  src/lib/api/search/useSearchCore.ts
  src/lib/api/search/useSearchLogic.ts
  src/lib/types/search/SearchResponseDto.ts
  src/lib/types/search/SearchSuggestionDto.ts
Labels: new-feature

#200 fix vote.ts 401error 처리
  src/lib/api/voting/vote.ts
Labels: bugfix

#203 refactor: BASE URL 적용
  src/lib/api/review/recommend.ts
  src/lib/api/review/review.ts
  src/lib/api/reviewComment/reviewComment.ts
  src/lib/api/search/searchApi.ts
  src/lib/api/security/useAuth.ts
  src/lib/api/user/user.ts
  src/lib/api/userActivity/logUserActivity.ts
  src/lib/api/voting/similar.ts
  src/lib/api/voting/vote.ts
  src/lib/api/webtoon/favorite.ts
  src/lib/api/webtoon/webtoon.ts
  src/lib/utils/apiConfig.ts
  src/lib/utils/constants.ts
Labels: execution-ok, refactor

#201 [Search] 자동완성 기능구현
  package-lock.json
  package.json
  src/app/feed/page.tsx
  src/app/search/page.tsx
  src/components/buisness/search/ResultOfReviewSearch.tsx
  src/components/buisness/search/ResultOfWebtoonsSearch.tsx
  src/components/buisness/search/ReviewSearchResults.tsx
  src/components/buisness/search/SearchByAllCategories.tsx
  src/components/buisness/search/SearchByNickName.tsx
  src/components/buisness/search/SearchByReview.tsx
  src/components/buisness/search/SearchByWebtoonName.tsx
  src/components/buisness/search/SearchContent.tsx
  src/components/buisness/search/SearchResultComponent.tsx
  src/components/buisness/search/WebtoonSearchResults.tsx
  src/components/common/Search/InfiniteScroll.tsx
  src/components/common/Search/PopularSearchTerms.tsx
  src/components/common/Search/SearchBar.tsx
  src/components/common/Search/SearchContainer.tsx
  src/components/common/Search/SearchTab.tsx
  src/components/common/Search/index.ts
  src/lib/api/search/api/search.ts
  src/lib/api/search/utils/searchMappings.ts
  src/lib/service/search/searchMappings.ts
  src/lib/service/search/searchTypes.ts
  src/lib/service/search/useSearchCore.ts
  src/lib/service/search/useSearchLogic.ts
  src/lib/service/search/useSearchService.ts
  src/lib/service/search/useSearchSuggestions.ts
  src/lib/service/search/useWebtoonSearchService.ts
  src/lib/types/search/SearchResponseDto.ts
  src/lib/types/search/SearchResult.ts
  src/lib/types/search/SuggestionItemDto.ts
Labels: execution-ok, new-feature
