Repository Dia218/webty-frontend-next, pull requests merged in 2025-02, with the labels that each got.

#14 Feat:WebtoonDetail 페이지 구현
  next.config.ts
  package-lock.json
  package.json
  src/app/webtoon-detail/[id]/ClientPage.tsx
  src/app/webtoon-detail/[id]/page.tsx
  src/app/webtoon-detail/page.tsx
  src/components/common/NavigationBar/NavigationBar.tsx
  src/components/ui/badge.tsx
  src/components/ui/card.tsx
  src/lib/api/user/user.ts
  src/lib/api/webtoon/webtoon.ts
Labels: new-feature

#16 feat : 테스트용 mypage 생성, 닉네임 수정 프로필사진 수정 모듈 구현
  .gitignore
  .prettierrc
  package-lock.json
  package.json
  public/uploads/iconmonstr-user-circle-thin-240.png
  src/app/mypage/page.tsx
  src/app/search/page.tsx
  src/app/search/webtoonPage.tsx
  src/components/common/NavigationBar/NavigationBar.tsx
  src/components/ui/dialog.tsx
  src/components/webtoon/webtoonItem.tsx
  src/components/webtoon/webtoonList.tsx
  src/components/webtoon/webtoonSearch.tsx
  src/lib/api/search/webtoonSearch.ts
  src/lib/api/user/user.ts
  src/lib/api/user/userProfile.ts
Labels: new-feature

#34 feat 상세웹툰페이지로 이동 추가
  src/components/webtoon/webtoonItem.tsx
Labels: new-feature

#36 refactor : 마이페이지 모듈화
  package-lock.json
  package.json
  src/app/mypage/page.tsx
  src/components/buisness/mypage/EditNickname.tsx
  src/components/buisness/mypage/ProfileSection.tsx
  src/components/ui/input.tsx
  src/components/ui/separator.tsx
  src/lib/api/user/userProfile.ts
Labels: refactor

#39 Fix: page.tsx 와 ClientPage.tsx 통합 및 WebtoonInfo.tsx 디자인 수정
  src/app/webtoon-detail/[id]/ClientPage.tsx
  src/app/webtoon-detail/[id]/page.tsx
  src/components/buisness/WebtoonDetail/WebtoonInfo.tsx
  src/components/common/FavoriteDialog/FavoriteDialog.tsx
Labels: ui-ux

#40 feat: 네비게이션바 경로에따라 요소 보이기 수정 & 경로및 파일명변경
  src/app/search/webtoonPage.tsx
  src/components/buisness/webtoon/WebtoonItem.tsx
  src/components/buisness/webtoon/WebtoonList.tsx
  src/components/buisness/webtoon/WebtoonSearch.tsx
  src/components/common/NavigationBar/NavigationBar.tsx
  src/components/common/NavigationBar/hiddenElements.ts
Labels: shared-feature, new-feature

#45 feature 웹툰리스트 가로정렬기능 추가 (디폴트 = 세로정렬)
  src/components/buisness/webtoon/WebtoonItem.tsx
  src/components/buisness/webtoon/WebtoonList.tsx
Labels: new-feature

#46 feat: Implement Drawer
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/app/mypage/page.tsx
  src/app/search/webtoonPage.tsx
  src/components/buisness/WebtoonDetail/WebtoonDrawerTaps.tsx
  src/components/buisness/mypage/UserDrawerTaps.tsx
  src/components/buisness/webtoon/WebtoonList.tsx
  src/components/common/ExpandableDrawer/ExpandableDrawer.stories.tsx
  src/components/common/ExpandableDrawer/ExpandableDrawer.tsx
  src/components/common/GhostTabs/GhostTabs.tsx
  src/components/ui/drawer.tsx
  src/components/ui/tabs.tsx
  src/lib/api/webtoon/favorite.ts
  src/lib/types/common/PageDto.ts
  src/lib/types/webtoon/WebtoonDetailDto.ts
  src/lib/types/webtoon/WebtoonResponseDto.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: no-impact, dependency-update, new-feature, refactor, rebuild

#51 feat : 글작성 모달 & rename : Webtoon 관련 코드컨벤션 적용
  package-lock.json
  src/app/search/page.tsx
  src/components/buisness/mypage/UserDrawerTaps.tsx
  src/components/buisness/search/webtoonPage.tsx
  src/components/common/NavigationBar/NavigationBar.tsx
  src/components/common/NavigationBar/hiddenElements.ts
  src/components/common/ReviewWriteModal/ReviewWriteModal.tsx
  src/components/common/webtoon/WebtoonItem.tsx
  src/components/common/webtoon/WebtoonList.tsx
  src/components/common/webtoon/WebtoonSearch.tsx
Labels: new-feature, refactor

#64 fix: WebtoonItem 진행중 -> 연재중
  src/components/common/webtoon/WebtoonItem.tsx
Labels: no-impact, typo-fix, ui-ux

#52 feat: Review 검색 추가
  src/app/search/page.tsx
  src/components/buisness/mypage/UserDrawerTaps.tsx
  src/components/buisness/review/EditReview.tsx
  src/components/buisness/search/ReviewSearchResult.tsx
  src/components/buisness/search/webtoonSearchResult.tsx
  src/components/common/Review/FeedReviewList.tsx
  src/components/common/Review/SmaillReviewItem.tsx
  src/components/common/ReviewWriteModal/ReviewWriteModal.tsx
  src/components/common/WebtoonList/WebtoonItem.tsx
  src/components/common/WebtoonList/WebtoonList.tsx
  src/components/common/reviewForm/ReviewForm.tsx
  src/components/common/webtoon/WebtoonSearch.tsx
  src/lib/api/search/feedReviewSearch.ts
  src/lib/types/review/FeedReviewResponseDto.ts
Labels: backend-sync, new-feature

#80 fix 섬네일 이동기능 제거
  src/components/common/WebtoonList/WebtoonItem.tsx
Labels: ui-ux

#79 fix ReviewWriteModal.tsx 문제 해결
  src/components/common/ReviewWriteModal/ReviewWriteModal.tsx
Labels: bugfix

#74 feat: Review 초벌작업
  src/app/review-detail/[id]/page.tsx
  src/app/review-detail/page.tsx
  src/lib/api/review/review.ts
  src/lib/types/review/ReviewDetailResponseDto.ts
Labels: new-feature

#89 fix: Review List, Review API, Review-detail
  package-lock.json
  src/app/feed/page.tsx
  src/app/review-detail/[id]/page.tsx
  src/app/webtoon-detail/[id]/page.tsx
  src/components/buisness/review/EditReview.tsx
  src/components/buisness/review/LargeReviewItem.tsx
  src/components/buisness/review/LargeReviewList.tsx
  src/components/common/ReviewForm/ReviewForm.tsx
  src/lib/api/review/review.ts
  src/lib/api/reviewComment/reviewComment.ts
  src/lib/types/common/PageDto.ts
  src/lib/types/review/ReviewDetailResponseDto.ts
  src/lib/types/review/ReviewRequestDto.ts
Labels: bugfix

#93 fix: Resolve WebtoonDetail Router Error & Fix Favorite Loading
  src/app/webtoon-detail/[id]/page.tsx
  src/components/buisness/webtoonDetail/WebtoonInfo.tsx
Labels: bugfix, critical-bug

#104 chore DTO & fix 개발환경중 조회수 2배 복사버그 수정
  src/app/review-detail/[id]/page.tsx
  src/components/common/LargeReview/LargeReviewItem.tsx
  src/components/common/SmallReviewList/SmallReviewItem.tsx
  src/lib/types/review/ReviewDetailResponseDto.ts
  src/lib/types/review/ReviewItemResponseDto.ts
Labels: bugfix, multiple-file-changes

#105 연재완료 -> 완결
  src/components/buisness/webtoonDetail/WebtoonInfo.tsx
Labels: no-impact

#109 feat: 수정삭제버튼 구현 (수정 내부 미구현)
  src/app/review-detail/[id]/page.tsx
  src/components/buisness/review/ReviewDetail.tsx
  src/components/common/UpdateDeleteButtons/UpdateDeleteButtons.tsx
  src/lib/api/review/review.ts
Labels: shared-feature, new-feature

#106 chore DTO 수정(백엔드와 동일) 및 기존 코드에 DTO 사용
  src/app/webtoon-detail/[id]/page.tsx
  src/components/buisness/webtoonDetail/WebtoonInfo.tsx
  src/lib/api/webtoon/webtoon.ts
  src/lib/types/webtoon/WebtoonDetailDto.ts
Labels: refactor

#113 Feat: 리뷰 수정 페이지 추가 , Fix : Feed Review Error
  package-lock.json
  src/app/layout.tsx
  src/app/review-update/[id]/page.tsx
  src/app/search/page.tsx
  src/components/buisness/review/FeedReview.tsx
  src/components/buisness/review/ReviewDetail.tsx
  src/components/buisness/review/UpdateReview.tsx
  src/components/common/ReviewForm/ReviewForm.tsx
  src/lib/api/review/review.ts
  src/lib/types/review/ReviewDetailResponseDto.ts
Labels: bugfix, new-feature

#114 feat: 추천 비추천 상태조회 및 등록 삭제 요청기능 추가
  src/app/review-detail/[id]/page.tsx
  src/components/buisness/review/ReviewDetail.tsx
  src/lib/api/review/recommend.ts
  src/lib/api/security/useAuth.ts
Labels: new-feature

#121 feat: ReviewRecommnedationBox
  src/components/buisness/review/ReviewDetail.tsx
  src/components/common/RecommendButton/ReviewRecommendBox.tsx
Labels: new-feature

#123 Feat/review/issue 118
  src/components/buisness/review/ReviewDetail.tsx
  src/components/buisness/review/ReviewInfo.tsx
  src/components/buisness/review/ReviewRecommendBox.tsx
Labels: new-feature

#127 Fix: 업데이트시 기존 이미지 삭제되지 않던 오류 수정
  src/components/buisness/review/UpdateReview.tsx
  src/components/common/ReviewForm/ReviewForm.tsx
Labels: bugfix

#130 chore: 마이페이지 버튼 로그인 상태에선 언제나 보이게
  src/components/common/NavigationBar/NavigationBar.tsx
  src/components/common/NavigationBar/hiddenElements.ts
Labels: execution-ok, ui-ux

#138 chore: userId 기능 추가
  src/app/review-detail/[id]/page.tsx
  src/components/buisness/review/ReviewDetail.tsx
  src/lib/api/security/useAuth.ts
Labels: shared-feature

#140 chore: ReviewRecommendBox
  src/components/buisness/review/ReviewDetail.tsx
  src/components/buisness/review/ReviewRecommendBox.tsx
Labels: improvement

#150 feat: WideReviewList 추가, RecommendedReviewBox 추가, recommend.ts 수정
  src/app/mypage/page.tsx
  src/components/buisness/mypage/UserDrawerTaps.tsx
  src/components/common/RecommendedReviewBox/RecommendedReviewBox.tsx
  src/components/common/SmallReviewList/SmallReviewList.tsx
  src/components/common/WideReviewList/WideReviewItem.tsx
  src/components/common/WideReviewList/WideReviewList.tsx
  src/lib/api/review/recommend.ts
Labels: shared-feature, new-feature

#153 feat : mypage 완성
  src/components/buisness/mypage/UserDrawerTaps.tsx
  src/components/common/RecommendedReviewBox/RecommendedReviewBox.tsx
  src/components/common/WideReviewBox/WideReviewBox.tsx
  src/lib/api/review/recommend.ts
  src/lib/api/review/review.ts
Labels: backend-sync, new-feature

#158 chore: 추천 ui/ux 경험 향상
  src/components/buisness/review/ReviewDetail.tsx
  src/components/buisness/review/ReviewRecommendBox.tsx
  src/components/common/RecommendButton/RecommendButton.tsx
Labels: ui-ux

#159 feat: webtoon-detail 게시글보기 추가
  src/app/webtoon-detail/[id]/page.tsx
  src/components/buisness/webtoonDetail/WebtoonDrawerTaps.tsx
  src/components/common/ResponsiveReviewBox/ResponsiveReviewBox.tsx
  src/lib/api/review/review.ts
Labels: backend-sync, new-feature

#160 refactor package LargeReview -> LargeReviewList
  src/app/search/page.tsx
  src/components/buisness/review/FeedReview.tsx
  src/components/common/LargeReviewList/LargeReviewItem.tsx
  src/components/common/LargeReviewList/LargeReviewList.tsx
Labels: typo-fix, refactor

#161 refactor: WebtoonSummaryDto 추가
  src/app/search/page.tsx
  src/components/buisness/review/ReviewDetail.tsx
  src/components/buisness/review/UpdateReview.tsx
  src/components/common/LargeReviewList/LargeReviewItem.tsx
  src/components/common/ReviewWebtoonBox/ReviewWebtoonBox.tsx
  src/components/common/SmallReviewList/SmallReviewItem.tsx
  src/components/common/WideReviewList/WideReviewItem.tsx
  src/lib/api/review/review.ts
  src/lib/types/review/ReviewDetailResponseDto.ts
  src/lib/types/review/ReviewItemResponseDto.ts
Labels: backend-sync

#163 [Feed] fix:threshold값 수정
  src/components/buisness/review/FeedReview.tsx
Labels: bugfix

#164 feat: 리뷰 스포일러 신고버튼
  src/components/buisness/review/ReviewContentBox.tsx
  src/components/common/LargeReviewList/LargeReviewItem.tsx
  src/components/common/SpoilerButton/SpoilerButton.tsx
  src/lib/api/review/review.ts
Labels: new-feature

#166 refactor webtoonAPI
  src/components/buisness/search/webtoonSearchResult.tsx
  src/components/common/ReviewWriteModal/ReviewWriteModal.tsx
  src/lib/api/search/webtoonSearch.ts
  src/lib/api/webtoon/webtoon.ts
Labels: refactor, multiple-file-changes

#167 refactor ReviewAPI
  src/components/buisness/search/ReviewSearchResult.tsx
  src/lib/api/review/review.ts
  src/lib/api/search/feedReviewSearch.ts
Labels: refactor

#168 rename ReviewWritePage & EditReview && build error solve
  src/app/review-write/page.tsx
  src/app/search/page.tsx
  src/components/buisness/review/EditReview.tsx
  src/components/common/ReviewWriteModal/ReviewWriteModal.tsx
Labels: no-impact, minor-bug

#172 feat: 댓글 대댓글 완성본
  src/app/review-detail/[id]/page.tsx
  src/components/common/CommentList/CommentArea.tsx
  src/components/common/CommentList/CommentItem.tsx
  src/components/common/CommentList/CommentList.tsx
  src/components/common/CommentList/MentionSuggestions.tsx
  src/components/common/CommentList/NestedCommentItem.tsx
  src/components/ui/comment-avatar.tsx
  src/components/ui/comment-container.tsx
  src/components/ui/comment-content.tsx
  src/components/ui/comment-header.tsx
  src/lib/api/reviewComment/reviewComment.ts
  src/lib/types/reviewComment/CommentResponseDto.ts
Labels: execution-ok, new-feature

#174 fix: 댓글조회 로그인문제 보완, 멘션기능 보완
  src/app/review-detail/[id]/page.tsx
  src/components/buisness/reviewComment/ReviewCommentSection.tsx
  src/components/common/CommentList/CommentItem.tsx
  src/components/common/CommentList/CommentList.tsx
  src/components/common/CommentList/MentionSuggestions.tsx
  src/components/common/CommentList/NestedCommentItem.tsx
  src/lib/api/reviewComment/reviewComment.ts
Labels: bugfix

#176 improvement: showing the guide-line in the unlogin case
  src/components/buisness/reviewComment/ReviewCommentSection.tsx
Labels: improvement

#178 [comment] requirement to the solving the button(cancel , modification) issue
  src/components/common/CommentList/NestedCommentItem.tsx
  src/lib/types/user/UserDataResponseDto.ts
Labels: hotfix
